/*
 Inverted IOC container v99

 https://github.com/philmander/inverted-js

 Copyright (c) 2013, Phil Mander
 Licensed under the MIT license
*/
"function"!==typeof define&&(define=require("amdefine")(module));
define("inverted/Util",function(){var g={isArray:function(b){return Array.isArray?Array.isArray(b):"[object Array]"===Object.prototype.toString.call(b)},inArray:function(b,d){if(d.indexOf)return d.indexOf(b);for(var a=0,e=d.length;a<e;a++)if(d[a]===b)return a;return-1},trim:function(b){return b?b.replace(/^\s+|\s+$/g,""):b},parseProtoReference:function(b){b=b.match(/^(.+?)(\[(.+?)\])?$/);return{protoId:g.trim(b[1]),interfaces:b[3]?g.splitCommaDelimited(b[3]):null}},matchProtoRefString:function(b){return"string"===
typeof b&&null!==b.match(/^\*[^\*]/)},splitCommaDelimited:function(b){return b?b.split(/\s*,\s*/):[]},warn:function(b){"undefined"!==typeof console&&console.warn&&(b instanceof Error?console.warn(b.message):console.warn(b))},createError:function(b){return new g.InvertedError(b)},InvertedError:function(b){this.message=b}};g.InvertedError.prototype=Error.prototype;g.InvertedError.prototype.print=function(){g.warn(this.message)};return g});
define("inverted/Promise",function(){var g=function(b){this._ctx=b;this._sucesses=[];this._failures=[]};g.prototype.then=function(b,d){"function"===typeof b&&this._sucesses.push(b);"function"===typeof d&&this._failures.push(d)};g.prototype.notifySuccess=function(b){for(var d=0;d<this._sucesses.length;d++)this._sucesses[d].apply(this._ctx,b)};g.prototype.notifyFailure=function(b){for(var d=0;d<this._failures.length;d++)this._failures[d].call(this._ctx,b)};return g});
define("inverted/ProtoFactory",["inverted/Util"],function(g){var b=function(d){this.config=d;this.appContext=null;this.injectAppContext=!0===this.config.injectAppContext?!0:!1;this.dependencyMap={}};b.prototype.addDependencies=function(d){for(var a in d)d.hasOwnProperty(a)&&(this.dependencyMap[a]=d[a])};b.prototype.getProto=function(d){d=g.parseProtoReference(d);var a=this.getProtoConfig(d.protoId),e=null;"static"===a.scope?"string"===typeof a.module&&(e=this.dependencyMap[a.module]):!a.scope||"singleton"!==
a.scope||"singleton"===a.scope&&!a.instance?(e=this._createInstance(a.module,a.args,a.props,a.extendsRef,a.mixin,!0===this.injectAppContext&&!1!==a.injectAppContext||!0!==this.injectAppContext&&!0===a.injectAppContext,d.interfaces),a.scope&&"singleton"===a.scope&&(a.instance=e)):e=a.instance;return e};b.prototype._createInstance=function(d,a,e,h,c,b,j){var f=null,f=this.dependencyMap[d];a=this._createArgs(a);h&&this._extendProto(f,this.getProto(h));j&&this._checkImplements(d,f.prototype,j);switch(a.length){case 0:f=
new f;break;case 1:f=new f(a[0]);break;case 2:f=new f(a[0],a[1]);break;case 3:f=new f(a[0],a[1],a[2]);break;case 4:f=new f(a[0],a[1],a[2],a[3]);break;case 5:f=new f(a[0],a[1],a[2],a[3],a[4]);break;case 6:f=new f(a[0],a[1],a[2],a[3],a[4],a[5]);break;case 7:f=new f(a[0],a[1],a[2],a[3],a[4],a[5],a[6]);break;case 8:f=new f(a[0],a[1],a[2],a[3],a[4],a[5],a[6],a[7]);break;case 9:f=new f(a[0],a[1],a[2],a[3],a[4],a[5],a[6],a[7],a[8]);break;case 10:f=new f(a[0],a[1],a[2],a[3],a[4],a[5],a[6],a[7],a[8],a[9]);
break;default:throw g.createError("Could not instantiate proto. Instances have a 10 arg limit");}if(e)for(var l in e)e.hasOwnProperty(l)&&(d=this._createArgs([e[l]]),"function"===typeof f[l]?(d[0]=g.isArray(d[0])?d[0]:[d[0]],f[l].apply(f,d[0])):f[l]=d[0]);if(c&&c.length){l=c.length;for(e=0;e<l;e++)h=c[e],d="string"===typeof h?h:h.ref,h="boolean"===typeof h.override?h.override:!0,this._mixin(f,this.getProto(d),d,h)}this.appContext&&b&&(f.__appContext__=this.appContext);return f};b.prototype._getProtoFromFactory=
function(d,a){var e=this.getProto(d);if(a)return e[a].apply(e);throw g.createError("No factory method defined with "+d);};b.prototype._createArgs=function(d){var a=[];if(d)for(var e,h=0;h<d.length;h++){var c=d[h];if(null===c||"undefined"===typeof c)a[h]=c;else if((e="object"===typeof c&&!g.isArray(c))&&c.ref||g.matchProtoRefString(c))e=c.ref||c.substr(1),a[h]=this.getProto(e);else if(e&&c.factoryRef)a[h]=this._getProtoFromFactory(c.factoryRef,c.factoryMethod);else if(e&&c.module)a[h]=this._createInstance(c.module,
c.args,c.props,c.extendsRef,c.mixin,c.injectAppContext,c.interfaces);else if(e){a[h]={};for(var b in c)c.hasOwnProperty(b)&&((e=c[b])&&(e.ref||g.matchProtoRefString(e))?(e=e.ref||e.substr(1),a[h][b]=this.getProto(e)):a[h][b]=e&&e.factoryRef?this._getProtoFromFactory(e.factoryRef,e.factoryMethod):e&&e.module?this._createInstance(e.module,e.args,e.props,e.extendsRef,e.mixin,c.injectAppContext,c.interfaces):e)}else a[h]=c}return a};b.prototype._extendProto=function(d,a){var e={},h;for(h in d.prototype)e[h]=
d.prototype[h];d.prototype=a;d.prototype._super=a.constructor;for(var c in e)d.prototype[c]=e[c];d.prototype.constructor=d};b.prototype._mixin=function(d,a,e,h){for(var c in a)"function"===typeof a[c]&&(!(c in d)||c in d&&h)&&function(c){d[c]=function(){return a[c].apply(a,arguments)}}(c);d["__"+e+"__"]=a};b.prototype._checkImplements=function(d,a,e){var h,c,b,j,f;for(h=0;h<e.length;h++){b=this.getInterfaceConfig(e[h]);f=[];for(c=0;c<b.length;c++)j=g.trim(b[c]),"function"!==typeof a[j]&&f.push(d+
" does not implement the method '"+j+"'");if(f.length)throw g.createError("Interface [ "+e[h]+"] not implemented: \n\t"+f.join("\n\t"));}};b.prototype.getProtoConfig=function(d){var a=this.config.protos;d=g.trim(d);if(a&&a.hasOwnProperty(d))return a[d];throw g.createError("No proto is defined for ["+d+"]");};b.prototype.getInterfaceConfig=function(d){var a=this.config.interfaces;d=g.trim(d);if(a&&a.hasOwnProperty(d))return a[d];throw g.createError("No interface is defined for ["+d+"]");};return b});
define("inverted/AppContext",["inverted/ProtoFactory","inverted/Promise","inverted/Util"],function(g,b,d){var a=function(a,d,c){this.config=a;this.protoFactory=d;this.originalModule=c||module;define.amd?"undefined"!==typeof requirejs?this._loader=require:"undefined"!==typeof curl&&(this._loader=curl):this._loader=this._commonRequire};a.create=function(d,h){var c=new g(d),b=new a(d,c,h);return c.appContext=b};a.loader=function(a){this._loader=a};a.prototype.getProto=function(a,h,c){var g=this,j=new b;
if(!this._loader)throw Error("No AMD loader is defined");if("string"===typeof h)throw d.createError('Inverted\'s interface has changed. Please now pass proto ID\'s as an array in a single argument\n\tgetProto(["one", "two","three"], onSuccess, onError);');"string"===typeof a&&(a=[a]);for(var f=[],l=[],k=0;k<a.length;k++)try{l=l.concat(this._getDependencies(a[k]))}catch(n){f.push(n)}this._loader(l,function(){var b={};for(k=0;k<l.length;k++)b[l[k]]=arguments[k];g.protoFactory.addDependencies(b);var b=
[],m;for(k=0;k<a.length;k++)try{m=g.protoFactory.getProto(a[k]),b.push(m)}catch(n){f.push(n)}for(k=0;k<f.length;k++)if(m=f[k],m instanceof d.InvertedError)"function"===typeof c&&c.call(g,m),j.notifyFailure(m),m.print();else throw m;"function"===typeof h&&h.apply(g,b);j.notifySuccess(b)});return j};a.prototype._getDependencies=function(a,b){b=b||[];var c=this.protoFactory.getProtoConfig(a);b.push(c.module);if(c.extendsRef){var g=d.parseProtoReference(c.extendsRef).protoId;b=this._getDependencies(g,
b)}c.args&&(b=this._getDependenciesFromArgs(c.args,b));if(c.props)for(var j in c.props)c.props.hasOwnProperty(j)&&(b=this._getDependenciesFromArgs([c.props[j]],b));if(c.mixin&&c.mixin.length){j=c.mixin.length;for(var f,g=0;g<j;g++)f=c.mixin[g],f="string"===typeof f?f:f.ref,f=d.parseProtoReference(f).protoId,b=this._getDependencies(f,b)}return b};a.prototype._getDependenciesFromArgs=function(a,b){if(a)for(var c,g=0;g<a.length;g++){var j=a[g];if(!(null===j||"undefined"===typeof j))if((c="object"===
typeof j)&&j.ref||d.matchProtoRefString(j))c=d.parseProtoReference(j.ref||j.substr(1)).protoId,b=this._getDependencies(c,b);else if(c&&j.factoryRef)b=this._getDependencies(j.factoryRef,b);else if(c&&j.module)b.push(j.module);else if(c)for(var f in j)j.hasOwnProperty(f)&&((c=j[f])&&(c.ref||d.matchProtoRefString(c))?(c=d.parseProtoReference(c.ref||c.substr(1)).protoId,b=this._getDependencies(c,b)):c&&c.factoryRef?b=this._getDependencies(c.factoryRef,b):c&&c.module&&b.push(c.module))}return b};a.prototype._commonRequire=
function(a,b){var c=this,d=[];a.forEach(function(a){d.push(c.originalModule.require(a))});b.apply(this,d)};return a});define(["inverted/AppContext"],function(g){return g});