/*
 Inverted IOC container v0.2.0

 https://github.com/philmander/inverted-js

 Copyright (c) 2013, Phil Mander
 Licensed under the MIT license
*/
"function"!==typeof define&&(define=require("amdefine")(module));
define("inverted/Util",function(){var f={isArray:function(b){return Array.isArray?Array.isArray(b):"[object Array]"===Object.prototype.toString.call(b)},inArray:function(b,c){if(c.indexOf)return c.indexOf(b);for(var a=0,e=c.length;a<e;a++)if(c[a]===b)return a;return-1},trim:function(b){return b?b.replace(/^\s+|\s+$/g,""):b},parseProtoReference:function(b){b=b.match(/^(.+?)(\[(.+?)\])?$/);return{protoId:f.trim(b[1]),interfaces:b[3]?f.splitCommaDelimited(b[3]):null}},matchProtoRefString:function(b){return"string"===
typeof b&&null!==b.match(/^\*[^\*]/)},splitCommaDelimited:function(b){return b?b.split(/\s*,\s*/):[]}};return f});
define("inverted/Promise",function(){var f=function(b){this._ctx=b;this._sucesses=[];this._failures=[]};f.prototype.then=function(b,c){"function"===typeof b&&this._sucesses.push(b);"function"===typeof c&&this._failures.push(c)};f.prototype.notifySuccess=function(b){for(var c=0;c<this._sucesses.length;c++)this._sucesses[c].apply(this._ctx,b)};f.prototype.notifyFailure=function(b){for(var c=0;c<this._failures.length;c++)this._failures[c].call(this._ctx,b)};return f});
define("inverted/ProtoFactory",["inverted/Util"],function(f){var b=function(c){this.config=c;this.appContext=null;this.injectAppContext=!0===this.config.injectAppContext?!0:!1;this.dependencyMap={}};b.prototype.addDependencies=function(c){for(var a in c)c.hasOwnProperty(a)&&(this.dependencyMap[a]=c[a])};b.prototype.getProto=function(c){c=f.parseProtoReference(c);var a=this.getProtoConfig(c.protoId),e=null;"static"===a.scope?"string"===typeof a.module&&(e=this.dependencyMap[a.module]):!a.scope||"singleton"!==
a.scope||"singleton"===a.scope&&!a.instance?(e=this._createInstance(a.module,a.args,a.props,a.extendsRef,!0===this.injectAppContext&&!1!==a.injectAppContext||!0!==this.injectAppContext&&!0===a.injectAppContext,c.interfaces),a.scope&&"singleton"===a.scope&&(a.instance=e)):e=a.instance;return e};b.prototype._createInstance=function(c,a,e,j,g,d){var h=null,h=this.dependencyMap[c];a=this._createArgs(a);j&&this._extendProto(h,this.getProto(j));d&&this._checkImplements(c,h.prototype,d);switch(a.length){case 0:h=
new h;break;case 1:h=new h(a[0]);break;case 2:h=new h(a[0],a[1]);break;case 3:h=new h(a[0],a[1],a[2]);break;case 4:h=new h(a[0],a[1],a[2],a[3]);break;case 5:h=new h(a[0],a[1],a[2],a[3],a[4]);break;case 6:h=new h(a[0],a[1],a[2],a[3],a[4],a[5]);break;case 7:h=new h(a[0],a[1],a[2],a[3],a[4],a[5],a[6]);break;case 8:h=new h(a[0],a[1],a[2],a[3],a[4],a[5],a[6],a[7]);break;case 9:h=new h(a[0],a[1],a[2],a[3],a[4],a[5],a[6],a[7],a[8]);break;case 10:h=new h(a[0],a[1],a[2],a[3],a[4],a[5],a[6],a[7],a[8],a[9]);
break;default:throw Error("Instances have 10 arg limit");}if(e)for(var b in e)e.hasOwnProperty(b)&&(c=this._createArgs([e[b]]),"function"===typeof h[b]?h[b].call(h,c[0]):h[b]=c[0]);this.appContext&&g&&(h.__appContext__=this.appContext);return h};b.prototype._getProtoFromFactory=function(c,a){var e=this.getProto(c);if(a)return e[a].apply(e);throw Error("No factory method defined with "+c);};b.prototype._createArgs=function(c){var a=[];if(c)for(var e,b=0;b<c.length;b++){var g=c[b];if(null===g||"undefined"===
typeof g)a[b]=g;else if((e="object"===typeof g)&&g.ref||f.matchProtoRefString(g))e=g.ref||g.substr(1),a[b]=this.getProto(e);else if(e&&g.factoryRef)a[b]=this._getProtoFromFactory(g.factoryRef,g.factoryMethod);else if(e&&g.module)a[b]=this._createInstance(g.module,g.args,g.props,null,g.injectAppContext,null);else if(e){a[b]={};for(var d in g)g.hasOwnProperty(d)&&((e=g[d])&&(e.ref||f.matchProtoRefString(e))?(e=e.ref||e.substr(1),a[b][d]=this.getProto(e)):a[b][d]=e&&e.factoryRef?this._getProtoFromFactory(e.factoryRef,
e.factoryMethod):e&&e.module?this._createInstance(e.module,e.args,e.props,null,g.injectAppContext,null):e)}else a[b]=g}return a};b.prototype._extendProto=function(c,a){var b={},j;for(j in c.prototype)b[j]=c.prototype[j];c.prototype=a;c.prototype._super=a.constructor;for(var g in b)c.prototype[g]=b[g];c.prototype.constructor=c};b.prototype._checkImplements=function(c,a,b){var j,g,d,h;for(j=0;j<b.length;j++){g=this.getInterfaceConfig(b[j]);d=f.splitCommaDelimited(g);h=[];for(g=0;g<d.length;g++)"function"!==
typeof a[d[g]]&&h.push(c+" does not implement the method '"+d[g]+"'");if(h.length)throw Error("Interface [ "+b[j]+"] not implemented: \n\t"+h.join("\n\t"));}};b.prototype.getProtoConfig=function(b){var a=this.config.protos;b=f.trim(b);if(a&&a.hasOwnProperty(b))return a[b];throw Error("No proto is defined for ["+b+"]");};b.prototype.getInterfaceConfig=function(b){var a=this.config.interfaces;b=f.trim(b);if(a&&a.hasOwnProperty(b))return a[b];throw Error("No interface is defined for ["+b+"]");};return b});
define("inverted/AppContext",["inverted/ProtoFactory","inverted/Promise","inverted/Util"],function(f,b,c){var a=function(a,b,d){this.config=a;this.protoFactory=b;this.originalModule=d||module;this._loader=define.amd&&"undefined"!==typeof requirejs?require:define.amd&&"undefined"!==typeof curl?curl:this._commonRequire};a.create=function(b,g){var d=new f(b),c=new a(b,d,g);return d.appContext=c};a.loader=function(a){this._loader=a};a.prototype.getProto=function(){var a=this,g=new b;if(!this._loader)throw Error("No AMD loader is defined");
var d=Array.prototype.slice.call(arguments,0),c;1<d.length&&"function"===typeof d[d.length-1]&&(c=d.pop());for(var k=[],f=0;f<d.length;f++)try{k=k.concat(this._getDependencies(d[f]))}catch(l){e(l.message),g.notifyFailure(l)}this._loader(k,function(){var b={};for(f=0;f<k.length;f++)b[k[f]]=arguments[f];a.protoFactory.addDependencies(b);var b=[],l;for(f=0;f<d.length;f++)try{l=a.protoFactory.getProto(d[f]),b.push(l)}catch(n){e(n.message),g.notifyFailure(n)}c&&c.apply(a,b);g.notifySuccess(b)});return g};
a.prototype._getDependencies=function(a,b){b=b||[];var d=this.protoFactory.getProtoConfig(a);b.push(d.module);if(d.extendsRef){var h=c.parseProtoReference(d.extendsRef).protoId;b=this._getDependencies(h,b)}d.args&&(b=this._getDependenciesFromArgs(d.args,b));if(d.props)for(var e in d.props)d.props.hasOwnProperty(e)&&(b=this._getDependenciesFromArgs([d.props[e]],b));return b};a.prototype._getDependenciesFromArgs=function(a,b){if(a)for(var d,e=0;e<a.length;e++){var f=a[e];if(!(null===f||"undefined"===
typeof f))if((d="object"===typeof f)&&f.ref||c.matchProtoRefString(f))d=c.parseProtoReference(f.ref||f.substr(1)).protoId,b=this._getDependencies(d,b);else if(d&&f.factoryRef)b=this._getDependencies(f.factoryRef,b);else if(d&&f.module)b.push(f.module);else if(d)for(var m in f)f.hasOwnProperty(m)&&((d=f[m])&&(d.ref||c.matchProtoRefString(d))?(d=c.parseProtoReference(d.ref||d.substr(1)).protoId,b=this._getDependencies(d,b)):d&&d.factoryRef?b=this._getDependencies(d.factoryRef,b):d&&d.module&&b.push(d.module))}return b};
a.prototype._commonRequire=function(a,b){var c=this,e=[];a.forEach(function(a){e.push(c.originalModule.require(a))});b.apply(this,e)};var e=function(a){"undefined"!==typeof console&&console.warn&&console.warn(a)};return a});define(["inverted/AppContext"],function(f){return f});