/*
 Inverted IOC container v99

 https://github.com/philmander/inverted-js

 Copyright (c) 2013, Phil Mander
 Licensed under the MIT license
*/
"function"!==typeof define&&(define=require("amdefine")(module));
define("inverted/Util",function(){var g={isArray:function(b){return Array.isArray?Array.isArray(b):"[object Array]"===Object.prototype.toString.call(b)},inArray:function(b,c){if(c.indexOf)return c.indexOf(b);for(var a=0,e=c.length;a<e;a++)if(c[a]===b)return a;return-1},trim:function(b){return b?b.replace(/^\s+|\s+$/g,""):b},parseProtoReference:function(b){b=b.match(/^(.+?)(\[(.+?)\])?$/);return{protoId:g.trim(b[1]),interfaces:b[3]?g.splitCommaDelimited(b[3]):null}},matchProtoRefString:function(b){return"string"===
typeof b&&null!==b.match(/^\*[^\*]/)},splitCommaDelimited:function(b){return b?b.split(/\s*,\s*/):[]},warn:function(b){"undefined"!==typeof console&&console.warn&&(b instanceof Error?console.warn(b.message):console.warn(b))},createError:function(b){return new g.InvertedError(b)},InvertedError:function(b){this.message=b}};g.InvertedError.prototype=Error.prototype;g.InvertedError.prototype.print=function(){g.warn(this.message)};return g});
define("inverted/Promise",function(){var g=function(b){this._ctx=b;this._sucesses=[];this._failures=[]};g.prototype.then=function(b,c){"function"===typeof b&&this._sucesses.push(b);"function"===typeof c&&this._failures.push(c)};g.prototype.notifySuccess=function(b){for(var c=0;c<this._sucesses.length;c++)this._sucesses[c].apply(this._ctx,b)};g.prototype.notifyFailure=function(b){for(var c=0;c<this._failures.length;c++)this._failures[c].call(this._ctx,b)};return g});
define("inverted/ProtoFactory",["inverted/Util"],function(g){var b=function(c){this.config=c;this.appContext=null;this.injectAppContext=!0===this.config.injectAppContext?!0:!1;this.dependencyMap={}};b.prototype.addDependencies=function(c){for(var a in c)c.hasOwnProperty(a)&&(this.dependencyMap[a]=c[a])};b.prototype.getProto=function(c){c=g.parseProtoReference(c);var a=this.getProtoConfig(c.protoId),e=null;"static"===a.scope?"string"===typeof a.module&&(e=this.dependencyMap[a.module]):!a.scope||"singleton"!==
a.scope||"singleton"===a.scope&&!a.instance?(e=this._createInstance(a.module,a.args,a.props,a.extendsRef,a.mixin,!0===this.injectAppContext&&!1!==a.injectAppContext||!0!==this.injectAppContext&&!0===a.injectAppContext,c.interfaces),a.scope&&"singleton"===a.scope&&(a.instance=e)):e=a.instance;return e};b.prototype._createInstance=function(c,a,e,h,d,b,j){var f=null,f=this.dependencyMap[c];a=this._createArgs(a);h&&this._extendProto(f,this.getProto(h));j&&this._checkImplements(c,f.prototype,j);switch(a.length){case 0:f=
new f;break;case 1:f=new f(a[0]);break;case 2:f=new f(a[0],a[1]);break;case 3:f=new f(a[0],a[1],a[2]);break;case 4:f=new f(a[0],a[1],a[2],a[3]);break;case 5:f=new f(a[0],a[1],a[2],a[3],a[4]);break;case 6:f=new f(a[0],a[1],a[2],a[3],a[4],a[5]);break;case 7:f=new f(a[0],a[1],a[2],a[3],a[4],a[5],a[6]);break;case 8:f=new f(a[0],a[1],a[2],a[3],a[4],a[5],a[6],a[7]);break;case 9:f=new f(a[0],a[1],a[2],a[3],a[4],a[5],a[6],a[7],a[8]);break;case 10:f=new f(a[0],a[1],a[2],a[3],a[4],a[5],a[6],a[7],a[8],a[9]);
break;default:throw g.createError("Could not instantiate proto. Instances have a 10 arg limit");}if(e)for(var l in e)e.hasOwnProperty(l)&&(c=this._createArgs([e[l]]),"function"===typeof f[l]?(c[0]=g.isArray(c[0])?c[0]:[c[0]],f[l].apply(f,c[0])):f[l]=c[0]);if(d&&d.length){l=d.length;for(e=0;e<l;e++)h=d[e],c="string"===typeof h?h:h.ref,h="boolean"===typeof h.override?h.override:!0,this._mixin(f,this.getProto(c),c,h)}this.appContext&&b&&(f.__appContext__=this.appContext);return f};b.prototype._getProtoFromFactory=
function(c,a){var e=this.getProto(c);if(a)return e[a].apply(e);throw g.createError("No factory method defined with "+c);};b.prototype._createArgs=function(c){var a=[];if(c)for(var e,h=0;h<c.length;h++){var d=c[h];if(null===d||"undefined"===typeof d)a[h]=d;else if((e="object"===typeof d)&&d.ref||g.matchProtoRefString(d))e=d.ref||d.substr(1),a[h]=this.getProto(e);else if(e&&d.factoryRef)a[h]=this._getProtoFromFactory(d.factoryRef,d.factoryMethod);else if(e&&d.module)a[h]=this._createInstance(d.module,
d.args,d.props,d.extendsRef,d.mixin,d.injectAppContext,null);else if(e){a[h]={};for(var b in d)d.hasOwnProperty(b)&&((e=d[b])&&(e.ref||g.matchProtoRefString(e))?(e=e.ref||e.substr(1),a[h][b]=this.getProto(e)):a[h][b]=e&&e.factoryRef?this._getProtoFromFactory(e.factoryRef,e.factoryMethod):e&&e.module?this._createInstance(e.module,e.args,e.props,e.extendsRef,e.mixin,d.injectAppContext,null):e)}else a[h]=d}return a};b.prototype._extendProto=function(c,a){var e={},h;for(h in c.prototype)e[h]=c.prototype[h];
c.prototype=a;c.prototype._super=a.constructor;for(var d in e)c.prototype[d]=e[d];c.prototype.constructor=c};b.prototype._mixin=function(c,a,e,h){for(var d in a)"function"===typeof a[d]&&(!(d in c)||d in c&&h)&&function(d){c[d]=function(){return a[d].apply(a,arguments)}}(d);c["__"+e+"__"]=a};b.prototype._checkImplements=function(c,a,e){var h,d,b,j,f;for(h=0;h<e.length;h++){b=this.getInterfaceConfig(e[h]);f=[];for(d=0;d<b.length;d++)j=g.trim(b[d]),"function"!==typeof a[j]&&f.push(c+" does not implement the method '"+
j+"'");if(f.length)throw g.createError("Interface [ "+e[h]+"] not implemented: \n\t"+f.join("\n\t"));}};b.prototype.getProtoConfig=function(c){var a=this.config.protos;c=g.trim(c);if(a&&a.hasOwnProperty(c))return a[c];throw g.createError("No proto is defined for ["+c+"]");};b.prototype.getInterfaceConfig=function(c){var a=this.config.interfaces;c=g.trim(c);if(a&&a.hasOwnProperty(c))return a[c];throw g.createError("No interface is defined for ["+c+"]");};return b});
define("inverted/AppContext",["inverted/ProtoFactory","inverted/Promise","inverted/Util"],function(g,b,c){var a=function(a,c,d){this.config=a;this.protoFactory=c;this.originalModule=d||module;this._loader=define.amd&&"undefined"!==typeof requirejs?require:define.amd&&"undefined"!==typeof curl?curl:this._commonRequire};a.create=function(c,h){var d=new g(c),b=new a(c,d,h);return d.appContext=b};a.loader=function(a){this._loader=a};a.prototype.getProto=function(a,h,d){var g=this,j=new b;if(!this._loader)throw Error("No AMD loader is defined");
if(!c.isArray(a))throw c.createError('Inverted\'s interface has changed. Please now pass proto ID\'s as an array in a single argument\n\tgetProto(["one", "two","three"], onSuccess, onError);');for(var f=[],l=[],k=0;k<a.length;k++)try{l=l.concat(this._getDependencies(a[k]))}catch(n){f.push(n)}this._loader(l,function(){var b={};for(k=0;k<l.length;k++)b[l[k]]=arguments[k];g.protoFactory.addDependencies(b);var b=[],m;for(k=0;k<a.length;k++)try{m=g.protoFactory.getProto(a[k]),b.push(m)}catch(n){f.push(n)}for(k=
0;k<f.length;k++)if(m=f[k],m instanceof c.InvertedError)"function"===typeof d&&d.call(g,m),j.notifyFailure(m),m.print();else throw m;"function"===typeof h&&h.apply(g,b);j.notifySuccess(b)});return j};a.prototype._getDependencies=function(a,b){b=b||[];var d=this.protoFactory.getProtoConfig(a);b.push(d.module);if(d.extendsRef){var g=c.parseProtoReference(d.extendsRef).protoId;b=this._getDependencies(g,b)}d.args&&(b=this._getDependenciesFromArgs(d.args,b));if(d.props)for(var j in d.props)d.props.hasOwnProperty(j)&&
(b=this._getDependenciesFromArgs([d.props[j]],b));if(d.mixin&&d.mixin.length){j=d.mixin.length;for(var f,g=0;g<j;g++)f=d.mixin[g],f="string"===typeof f?f:f.ref,f=c.parseProtoReference(f).protoId,b=this._getDependencies(f,b)}return b};a.prototype._getDependenciesFromArgs=function(a,b){if(a)for(var d,g=0;g<a.length;g++){var j=a[g];if(!(null===j||"undefined"===typeof j))if((d="object"===typeof j)&&j.ref||c.matchProtoRefString(j))d=c.parseProtoReference(j.ref||j.substr(1)).protoId,b=this._getDependencies(d,
b);else if(d&&j.factoryRef)b=this._getDependencies(j.factoryRef,b);else if(d&&j.module)b.push(j.module);else if(d)for(var f in j)j.hasOwnProperty(f)&&((d=j[f])&&(d.ref||c.matchProtoRefString(d))?(d=c.parseProtoReference(d.ref||d.substr(1)).protoId,b=this._getDependencies(d,b)):d&&d.factoryRef?b=this._getDependencies(d.factoryRef,b):d&&d.module&&b.push(d.module))}return b};a.prototype._commonRequire=function(a,b){var c=this,g=[];a.forEach(function(a){g.push(c.originalModule.require(a))});b.apply(this,
g)};return a});define(["inverted/AppContext"],function(g){return g});